---
rules:
  at-rule-blacklist:
    - debug
  at-rule-empty-line-before:
    - always
    - except:
        - inside-block
        - blockless-after-same-name-blockless
  at-rule-name-case: lower
  at-rule-name-space-after: always-single-line
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - '/include/'
        - '/mixin/'
        - '/if/'
        - '/else/'
        - '/each/'
        - '/function/'
        - '/return/'
        - '/for/'
        - '/extend/'
        - '/error/'
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  block-closing-brace-empty-line-before:
    - never
    - severity: error
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
        - if
        - else
        - for
        - each
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-no-empty:
    - true
    - severity: error
  block-opening-brace-newline-after: always
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  color-hex-case: lower
  color-hex-length: long
  color-named:
    - never
    - severity: warning
  color-no-invalid-hex: true
  color-no-hex: true
  comment-no-empty: true
  comment-whitespace-inside: always
  custom-property-empty-line-before:
    - always
    - except:
        - after-comment
        - after-custom-property
        - first-nested
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  declaration-no-important: true
  declaration-property-unit-blacklist:
    font-size:
      - px
    '/^animation/':
      - s
    '/^transition':
      - s
  declaration-property-unit-whitelist:
    font-size:
      - em
      - rem
    '/^animation/':
      - ms
    '/^transition':
      - ms
  font-family-name-quotes: always-unless-keyword
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  font-weight-notation: numeric
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case:
    - lower
    - ignoreFunctions:
        - '/^get.*$/'
        - '/^set.*$/'
  function-parentheses-newline-inside: never-multi-line
  function-parentheses-space-inside: never
  function-url-quotes: never
  function-whitespace-after: always
  indentation:
    - 2
    - indentClosingBrace: false
  keyframe-declaration-no-important: true
  keyframes-name-pattern: '/(^[a-z]*)+[A-Z]+[a-z]*$/'
  length-zero-no-unit: true
  max-empty-lines:
    - 1
    - ignore:
        - comments
  max-nesting-depth:
    - 50
    - severity: warning
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-first-line: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
  number-leading-zero: always
  number-max-precision: 6
  number-no-trailing-zeros: true
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  rule-empty-line-before:
    - always
    - except:
        - inside-block
      ignore:
        - after-comment
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-max-attribute: 3
  selector-max-class: 4
  selector-max-combinators: 4
  selector-max-compound-selectors: 4
  selector-max-empty-lines: 0
  selector-max-id: 0
  selector-max-specificity: '0,5,0'
  selector-max-universal: 3
  selector-no-qualifying-type: true
  selector-no-vendor-prefix: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation:
    - double
    - severity: error
  selector-pseudo-element-no-unknown: true
  selector-pseudo-element-blacklist:
    - 'ng-deep'
    - severity: error
  selector-type-case: lower
  selector-type-no-unknown: true
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: single
  time-min-milliseconds: 150
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix:
    - true
    - severity: warning
